spring:
  application:
    name: aws-lambda

aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  region: ${AWS_REGION}
  s3:
    endpoint: ${AWS_S3_ENDPOINT}
    bucket: ${AWS_S3_BUCKET}}
  dynamodb:
    table-name: ${AWS_DYNAMODB_TABLE_NAME}}